language: go

go:
  - "1.14"

os:
  - linux

git:
  depth: 1
  quiet: true
  submodules: false

notifications:
  email: false

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    - BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"

stages:
  - name: Build
  - name: Lint

jobs:
  include:
    - stage: "Build"
      name: "build"
      script: make build

    - stage: "Build"
      name: "docker"
      script: make build-docker
