apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
data:
  registry-config.yml : |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    notifications:
      events:
        includereferences: true
      endpoints:
      - name: deployer
        disabled: false
        url: http://charon-deployer:31337/rollout
        timeout: 5s
        threshold: 10
        backoff: 30s
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
---
apiVersion: v1
kind: Pod
metadata:
  name: charon-registry
  labels:
    name: registry
spec:
  volumes:
    - name: config
      configMap:
        name: registry-config
        items:
          - key: registry-config.yml
            path: config.yml
  containers:
  - name: charon-registry
    image: registry:2
    ports:
    - name: registry-port
      containerPort: 5000
    volumeMounts:
        - name: config
          mountPath: /etc/docker/registry
---
apiVersion: v1
kind: Service
metadata:
  name: charon-registry
spec:
  type: ClusterIP
  selector:
    name: registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  externalIPs:
  - 10.11.12.1
