# permissions for end users to edit charons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: charon-editor-role
rules:
- apiGroups:
  - charon.charon.cr
  resources:
  - charons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charon.charon.cr
  resources:
  - charons/status
  verbs:
  - get
