# permissions for end users to view charons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: charon-viewer-role
rules:
- apiGroups:
  - charon.charon.cr
  resources:
  - charons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charon.charon.cr
  resources:
  - charons/status
  verbs:
  - get
