apiVersion: deployer.charon.cr/v1alpha1
kind: Deployer
metadata:
  name: charon-deployer
spec:
  deployerImage: charon-registry:5000/deployer
  analyzerImage: charon-registry:5000/analyzer
  serviceAccountName: charon-deployer-serv-acc
  mountPath: /var/run/secrets
  tokenName: deployer-secret
