apiVersion: deployer.charon.cr/v1alpha1
kind: Deployer
metadata:
  name: charon-deployer
  namespace: default
spec:
  analyzer: charon-analyzer
  deployerImage: f0m41h4u7/charon-deployer
  analyzerImage: f0m41h4u7/charon-analyzer
  serviceAccountName: charon-deployer-serv-acc
  mountPath: /var/run/secrets
  tokenName: deployer-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  PROMETHEUS_HOST: http://prometheus-service:9090
  REGISTRY: charon-registry:5000/

