apiVersion: v1
kind: ServiceAccount
metadata:
  name: charon-deployer-serv-acc
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: deployer-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "update", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-role-binding
subjects:
- kind: ServiceAccount
  name: charon-deployer-serv-acc
  namespace: default
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: ""
