apiVersion: v1
kind: ServiceAccount
metadata:
  name: charon-deployer-serv-acc
automountServiceAccountToken: false
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployer-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "update", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployer-role-binding
subjects:
- kind: ServiceAccount
  name: charon-deployer-serv-acc
  apiGroup: ""
  namespace: default
roleRef:
  kind: ClusterRole
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
