apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: charons.charon.charon.cr
spec:
  group: charon.charon.cr
  names:
    kind: Charon
    listKind: CharonList
    plural: charons
    singular: charon
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Charon is the Schema for the charons API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CharonSpec defines the desired state of Charon
          type: object
          properties:
            registry:                         
              format: string                         
              type: string                                                             
            image:               
              format: string                                                      
              type: string
            version:        
              format: string
              type: string
            version_changed:
              format: bool
              type: bool
        status:
          description: CharonStatus defines the observed state of Charon
          type: object
          properties:
            registry:                                                                                                               
              format: string                         
              type: string                                                             
            image:             
              format: string                                                      
              type: string
            version:        
              format: string
              type: string
            version_changed:
              format: bool
              type: bool
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
